#!/bin/bash

# location of the JAVA command to use
JAVAC=/usr/bin/javac

# location of additional JAVA libraries to use
JAVALIB=/Applications/mipav/jre/Contents/Home/lib/ext/

# location of the MIPAV installation to use
MIPAV=/Applications/mipav

# location of the plugin installation to use
# please replace 'ThisUser' by your user name
PLUGINS=/Users/piloubazin/mipav/plugins

# location of the code
CODE=/Users/piloubazin/Code/github/cbstools-public

# mipav command
$JAVAC -classpath $CODE:$JAVALIB/*:$MIPAV:$MIPAV/lib/*:$PLUGINS:$/library/* -server -g -O -deprecation -encoding UTF-8 $@

